### ISSUE TITLE
DataContractシリアライザーが機能していない

### ISSUE THREAD

**Issue by indigo-san** [indigo-san/BEditor#10]
# 状態  
* DataContractシリアライザのコンストラクタにKnownTypesを指定しても、反映されない
* KnownTypeAttributeを使うとシリアル化できる  

# 問題点  
* Attributeは動的に変更できないのでプラグインによって追加されたエフェクトのシリアル化ができない

**Comment by yuto-trd** [comment]
バイナリだと保存できたのでバイナリに変更する
