### ISSUE TITLE
動画の入出力

### ISSUE THREAD

**Issue by indigo-san** [indigo-san/BEditor#11]
FFmpegを利用して動画の入出力をする  

1.xのリリースで追加

**Comment by indigo-san** [comment]
[開始](https://github.com/indigo-san/BEditor/commit/39309efb30994bec0f346ee5a793a4474ecd6fb5)

**Comment by yuto-trd** [comment]
### 使う可能性があるライブラリ

* FFmpeg
* VLC
* OpenCV(音声は取り出せない)

#### Windows
* [UWP](https://docs.microsoft.com/ja-jp/windows/uwp/audio-video-camera/transcode-media-files)
* Media Foundation

**Comment by yuto-trd** [comment]
[BEditor 0.0.4](https://github.com/indigo-san/BEditor/releases/tag/v0.0.4-alpha) のリリースに動画の入出力を含めたのでこのissueを閉じます
